file_name: './datasets/5seq/geo.csv'
specimen: 'id'   #"Please enter the name of the colum containing the specimens names: "
names: ['id', 'ALLSKY_SFC_SW_DWN', 'T2M', 'PRECTOTCORR', 'QV2M', 'WS10M']
bootstrap_threshold: 0
ls_threshold: 60
window_size: 200
step_size: 100
bootstrap_amount: 100
data_names: ['ALLSKY_SFC_SW_DWN_newick', 'T2M_newick', 'QV2M_newick', 'PRECTOTCORR_newick', 'WS10M_newick']
reference_gene_dir: './datasets/5seq'
reference_gene_file: 'seq small.fasta'
makeDebugFiles: True
